export type ContactData = {
  title: string;
  subtitle: string;
  phone?: string;
  mail: string;
  address?: string;
  phoneLabel?: string;
  mailLabel?: string;
  addressLabel?: string;
  imgUrl?: string;
  mapSrc?: string;
  contactAddress: boolean;
  contactEmail: boolean;
  contactPhone: boolean;
  nameField: boolean;
  emailField: boolean;
  phoneField: boolean;
  messageField: boolean;
  textColor: string;
  primaryLabel?: string;
};
